cache:
  time: 100
captcha:
  key-long: 6 # 验证码长度
  img-width: 240 # 宽度
  img-height: 80 # 高度
  dot-count: 80 # 干扰线点数
  max-skew: 0.7 # 倾斜度
local:
  path: uploads/file # 上传文件保存路径
  size: 10 # 上传文件大小单位M
mysql: # mysql 配置
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: server-fiber
  username: root
  password: "123456"
  skip-transaction: false # 是否禁用事务
  max-idle-conns: 100
  max-open-conns: 1000
  log-mode: silent # silent
  log-zap: true
  debug: true
redis: # redis 配置
  db: 0
  addr: 127.0.0.1
  password: ""
  port: "6379"
