// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

import (
	"github.com/gofiber/fiber/v2"
	"github.com/spf13/viper"
	"go.uber.org/zap"
	"server-fiber/init_load"
	"server-fiber/model"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp() (*init_load.RouterApp, func(), error) {
	viper, err := ViperInit()
	if err != nil {
		return nil, nil, err
	}
	logger, err := ZapInit(viper)
	if err != nil {
		return nil, nil, err
	}
	app := ProvideFiberApp(logger)
	db, err := init_load.ProvideGorm(logger)
	if err != nil {
		return nil, nil, err
	}
	redisInitialized, err := init_load.ProvideRedis(logger)
	if err != nil {
		return nil, nil, err
	}
	timerInitialized := init_load.ProvideTimer(db, logger)
	routerApp := init_load.ProvideRouter(app, db, logger, redisInitialized, timerInitialized)
	return routerApp, func() {
	}, nil
}

// wire.go:

// ViperInit 初始化 Viper
func ViperInit() (*viper.Viper, error) {
	return viperInit()
}

// ZapInit 初始化 Zap
func ZapInit(vip *viper.Viper) (*zap.Logger, error) {
	if err := vip.Unmarshal(&model.CONFIG); err != nil {
		return nil, err
	}
	model.VIP = vip
	logger, err := zapInit()
	if err != nil {
		return nil, err
	}
	model.LOG = logger
	return logger, nil
}

// ProvideFiberApp 提供 Fiber App
func ProvideFiberApp(logger *zap.Logger) *fiber.App {
	return fiber.New(model.RunCONFIG.FiberConfig)
}
