// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

import (
	"github.com/gofiber/fiber/v2"
	"github.com/spf13/viper"
	"go.uber.org/zap"
	"server-fiber/init_load"
	"server-fiber/model"
	"server-fiber/router"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp() (*init_load.RouterApp, func(), error) {
	viper, err := ViperInit()
	if err != nil {
		return nil, nil, err
	}
	logger, err := ZapInit(viper)
	if err != nil {
		return nil, nil, err
	}
	app := ProvideFiberApp(logger)
	db, err := init_load.ProvideGorm(logger)
	if err != nil {
		return nil, nil, err
	}
	redisInitialized, err := init_load.ProvideRedis(logger)
	if err != nil {
		return nil, nil, err
	}
	timerInitialized := init_load.ProvideTimer(db, logger)
	articleRouter := router.ProvideArticleRouter()
	commentRouter := router.ProvideCommentRouter()
	baseMessageRouter := router.ProvideBaseMessageRouter()
	userRouter := router.ProvideUserRouter()
	taskRouter := router.ProvideTaskRouter()
	tagRouter := router.ProvideTagRouter()
	likeRouter := router.ProvideLikeRouter()
	appRouter := router.ProvideAppGroup(articleRouter, commentRouter, baseMessageRouter, userRouter, taskRouter, tagRouter, likeRouter)
	apiRouter := router.ProvideApiRouter()
	githubRouter := router.ProvideGithubRouter()
	authorityBtnRouter := router.ProvideAuthorityBtnRouter()
	authorityRouter := router.ProvideAuthorityRouter()
	autoCodeHistoryRouter := router.ProvideAutoCodeHistoryRouter()
	autoCodeRouter := router.ProvideAutoCodeRouter()
	baseRouter := router.ProvideBaseRouter()
	casbinRouter := router.ProvideCasbinRouter()
	dictionaryDetailRouter := router.ProvideDictionaryDetailRouter()
	dictionaryRouter := router.ProvideDictionaryRouter()
	initRouter := router.ProvideInitRouter()
	jwtRouter := router.ProvideJwtRouter()
	menuRouter := router.ProvideMenuRouter()
	operationRecordRouter := router.ProvideOperationRecordRouter()
	problemRouter := router.ProvideProblemRouter()
	sysRouter := router.ProvideSysRouter()
	systemUserRouter := router.ProvideSystemUserRouter()
	systemRouter := router.ProvideSystemGroup(apiRouter, githubRouter, authorityBtnRouter, authorityRouter, autoCodeHistoryRouter, autoCodeRouter, baseRouter, casbinRouter, dictionaryDetailRouter, dictionaryRouter, initRouter, jwtRouter, menuRouter, operationRecordRouter, problemRouter, sysRouter, systemUserRouter)
	customerRouter := router.ProvideCustomerRouter()
	excelRouter := router.ProvideExcelRouter()
	fileUploadAndDownloadRouter := router.ProvideFileUploadAndDownloadRouter()
	exampleRouter := router.ProvideExampleGroup(customerRouter, excelRouter, fileUploadAndDownloadRouter)
	frontendRouter := router.ProvideFrontendRouter()
	routerFrontendRouter := router.ProvideFrontendGroup(frontendRouter)
	mobileLoginRouter := router.ProvideMobileLoginRouter()
	mobileUserRouter := router.ProvideMobileUserRouter()
	mobileRouter := router.ProvideMobileGroup(mobileLoginRouter, mobileUserRouter)
	routerApp := init_load.ProvideRouter(app, db, logger, redisInitialized, timerInitialized, appRouter, systemRouter, exampleRouter, routerFrontendRouter, mobileRouter)
	return routerApp, func() {
	}, nil
}

// wire.go:

// ViperInit 初始化 Viper
func ViperInit() (*viper.Viper, error) {
	return viperInit()
}

// ZapInit 初始化 Zap
func ZapInit(vip *viper.Viper) (*zap.Logger, error) {
	if err := vip.Unmarshal(&model.CONFIG); err != nil {
		return nil, err
	}
	model.VIP = vip
	logger, err := zapInit()
	if err != nil {
		return nil, err
	}
	model.LOG = logger
	return logger, nil
}

// ProvideFiberApp 提供 Fiber App
func ProvideFiberApp(logger *zap.Logger) *fiber.App {
	return fiber.New(model.RunCONFIG.FiberConfig)
}
